version: 2.1

jobs:
  hello:
    docker:
      - image: alpine
    steps:
      - run: echo "Hello, world! 👋"

workflows:
  welcome:
    triggers:
      - schedule:
          # This is every five minutes, just to test
          #
          # Interestingly, using the "*/5 * * * *" doesn't work. The validator
          # says it's not a valid POSIX syntax (circleci config validate)
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - trunk
                - ruby-script
    jobs:
      - hello
