version: 2.1

executors:
  ruby:
    docker:
      - image: circleci/ruby:2.7.1

jobs:
  test:
    executor: ruby
    steps:
      - checkout
      - run: bundle install && bundle exec rspec
  bintray_garbage_collection:
    executor: ruby
    steps:
      - checkout
      - run: bundle install && bundle exec ruby ./bin/bintray_garbage_collector.rb

workflows:
  test:
    jobs:
      - test
  bintray_garbage_collection:
    triggers:
      - schedule:
          # Every day, at 0 minute and 0 hour (midnight)
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - trunk
                - ruby-script
    jobs:
      - bintray_garbage_collection
