version: 2.1

executors:
  ruby:
    docker:
      - image: circleci/ruby:2.7.1

jobs:
  test:
    executor: ruby
    steps:
      - checkout
      - run: bundle install && bundle exec rspec
  hello:
    executor: ruby
    steps:
      - run: echo "Hello, world! 👋"

workflows:
  test:
    jobs:
      - test
  welcome:
    triggers:
      - schedule:
          # Every day, at 0 minute and 0 hour (midnight)
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - trunk
    jobs:
      - hello
