version: 2.1

executors:
  ruby:
    docker:
      - image: circleci/ruby:2.7.1

jobs:
  test:
    executor: ruby
    steps:
      - checkout
      - run: bundle install && bundle exec rspec
  bintray_garbage_collection:
    executor: ruby
    steps:
      - checkout
      - run: bundle install && bundle exec ruby ./bin/bintray_garbage_collector.rb

workflows:
  test:
    jobs:
      - test
  bintray_garbage_collection:
    triggers:
      - schedule:
          # Every five minutes, to test the behavior
          #
          # I tried to use "*/5" but `cicleci config validate` says that it's
          # not a valid POSIX syntax for cron jobs...
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - trunk
                # Add the name of this branch for the test
                - schedule-test
    jobs:
      - bintray_garbage_collection
