version: 2.1

jobs:
  bintray_garbage_collection:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run: bundle install && bundle exec ruby ./bintray-garbage-collector.rb

workflows:
  bintray_garbage_collection:
    triggers:
      - schedule:
          # This is every five minutes, just to test
          #
          # Interestingly, using the "*/5 * * * *" doesn't work. The validator
          # says it's not a valid POSIX syntax (circleci config validate)
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - trunk
                - ruby-script
    jobs:
      - bintray_garbage_collection
